create:
  path: /create-article
  controller: App\Controller\ArticleController::createArticle

view:
  path: /view-article/{id}
  controller: App\Controller\ArticleController::viewArticle

show:
  path: /show-articles
  controller: App\Controller\ArticleController::showArticles

delete:
  path: /delete-article/{id}
  controller: App\Controller\ArticleController::deleteArticle

update:
  path: /update-article/{id}
  controller: App\Controller\ArticleController::updateArticle